theme: jekyll-theme-minimal
title: Marie-Carline Chardonnet
author: CHARDONN
email: chardonnet@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
 Data-Driven Journalist
# social links
twitter_username: mcchardonnet # DO NOT include the @ character, or else the build will fail!
github_username:  CHARDONN # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
